### ISSUE TITLE
2주차 회의(sample)

### ISSUE THREAD

**Issue by sange17** [shinjuno123/Email-Manager#5]
### 미팅 날짜/시간/아젠다

 - 05/06/2024
 - 2시간
 - 화면 구성과 필요한 프레임워크

### Action Items

- 기한: 05/25/2024
- 디자인 완성 (@JKH1109 , @shinjuno123 , @sange17 )
- Oauth의 구현 방식에 대해서 조사 (@팀맴버이메일, @팀맴버이메일, @팀맴버이메일)
- ...etc

**Comment by sange17** [comment]
@JKH1109  권호 안녕

**Comment by JKH1109** [comment]
@sange17 권택상 바보
