### ISSUE TITLE
2주차 회의 07/27/2024

### ISSUE THREAD

**Issue by JKH1109** [shinjuno123/Email-Manager#8]
### 미팅 날짜/시간/아젠다

- 다음 미팅날짜 : 2024년 8월 3일
- @JKH1109  : 메인화면 작업 및 Prototype 1차 Test
- @shinjuno123 : Flutter 개발 세팅
- @sange17 : Figma 필터 Setting 화면 작업 + @
- @Diosong529 : Figma 작업

### 핵심 요약

- 2024년 07월 27일
- 정권호, 송전영 Github Project Assign Add
- Keyword Filter와 Email Filter를 같은 화면에서 Scorll Event를 통해 확인 및 작업할 수 있도록 구상
- Filter에 대한 하나 이상의 WorkSpace를 생성하여 관리할 수 있도록 구상
- Cancel 혹은 Save Button Click Event 발생 시 Main 화면으로 돌아오도록 구상
- 이 외 추가적인 Prototype구현 과정은 3차 회의 때 Figma 작업자들이 설명

### 관련 링크

- Figma WorkSpace : https://www.figma.com/design/ctUuXa3mNE8OiGQRheuIx2/Email-App?node-id=0-1&t=yCjG4kK7eNKn0CFz-0

### Action Items

- 기한: 08/03/2024
- Fimga 디자인 및 Prototype 작업 (@JKH1109 , @sange17)
- Flutter 개발 환경 Setting (@shinjuno123)

**Comment by shinjuno123** [comment]
@JKH1109  LGTM (Looks Good To me)
